global:
  loglevel: info
  apiRoute:
    enable: true
  http:
    listenaddr: :8084
    listenaddrtls: :18558
  tcp:
    listenaddr: :50054
  db:
    dsn: "test4.db"
    type: "sqlite"
  storage:
    s3:
      region: "us-east-1"                   # AWS区域
      endpoint: "storage-dev.xiding.tech"          # S3服务端点
      accessKeyID: "xidinguser"     # 访问密钥ID
      secretAccessKey: "U2FsdGVkX1/7uyvj0trCzSNFsfDZ66dMSAEZjNlvW1c=" # 秘密访问密钥
      bucket: "vidu-media-bucket"            # 存储桶名称
      pathPrefix: "recordings"     # 文件路径前缀
      forcePathStyle: true                 # 强制路径样式（MinIO需要设为true）
      useSSL: true                          # 是否使用SSL
      timeout: "600s"                        # 上传超时时间    
  # storage:
  #   s3:
  #     region: "us-east-1"
  #     endpoint: "s3.example.com"
  #     accessKeyID: "REPLACE_ME"
  #     secretAccessKey: "REPLACE_ME"
  #     bucket: "example-bucket"
  #     pathPrefix: ""
  #     forcePathStyle: true
  #     useSSL: true
  #     timeout: "600s"
rtmp:
  tcp:
    listenaddr: :19354
rtsp:
  tcp: :5544
gb28181:
  enable: false  
webrtc:
  port: udp:9400-9500  
webtransport:
  listenAddr: :4434
cascadeserver:
  quic:
    listenaddr: :44943
cluster:
  quic:
    listenaddr: :44943
  sync:
    serverid: "node4"
    address: "localhost:50054"
    seedservers:
      - "localhost:50051"
      - "localhost:50052"
      - "localhost:50053"
      - "localhost:50055"
    heartbeatinterval: 5s
    syncinterval: 30s
  role:
    - name: "internal"
      description: "内网角色"
      canAccess:
        - "public"
        - "relay"
      accessibleBy:
        - "internal"
        - "admin"
    - name: "public"
      description: "公网角色"
      canAccess:
        - "admin"
        - "storage"
      accessibleBy:
        - "internal"
        - "relay"
  # routing:
  #   redirect:
  #     "^test/":
  #       statusCode: 307
  #       forceredirect: true
  #       targetoverrides:
  #         node1: localhost:18081
  #         node2: localhost:18082
  #         node3: localhost:18083
  #         node4: localhost:18084
